### ISSUE TITLE
Left hand side of 𬢍 (U+2C88D) is 束

### ISSUE THREAD

**Issue by hfhchan** [hfhchan/irg#105]
![image](https://user-images.githubusercontent.com/8191296/36553252-cd72bb30-1836-11e8-809e-c12b158f9dec.png)
It is not simplified form of 𧠵.

**Comment by hfhchan** [comment]
@eisoch Need your scan

**Comment by eisoch** [comment]
![image](https://user-images.githubusercontent.com/24350864/36589098-2540936c-18c5-11e8-879e-5860553867e9.png)
The G glyph is correct.

**Comment by hfhchan** [comment]
Mislead by @kunki 😏
