### ISSUE TITLE
T-glyph for 鎿 (U+93BF) doesn't match TF-6143

### ISSUE THREAD

**Issue by mrhso** [hfhchan/irg#134]
Glyph in Code Chart:
![image](https://user-images.githubusercontent.com/13294467/39869350-c43cc4e4-548f-11e8-9e94-a326ccf49fd3.png)
Glyph in CNS 11643:
![image](https://user-images.githubusercontent.com/13294467/39869360-c9e6baf8-548f-11e8-84c7-b4b349ba9a2a.png)

**Comment by hfhchan** [comment]
Fixed in Unicode v13.0

**Comment by hfhchan** [comment]
Record from [zi.tools](https://zi.tools/zi/%E9%8E%BF):
<img width="216" alt="image" src="https://user-images.githubusercontent.com/8191296/197324321-d2491573-2df4-42e8-9833-007b1450003a.png">
