### ISSUE TITLE
T6-3F69 (U+2267B) is questionably designed

### ISSUE THREAD

**Issue by wtn** [hfhchan/irg#146]
<img width="658" alt="U+2267B" src="https://user-images.githubusercontent.com/35801/59324015-be7d8b00-8ca2-11e9-8044-9c1acc0d1ad2.png">

No other encoded ideographs with ⺻ look like this.

**Comment by hfhchan** [comment]
Hanyu Dazidian quotes from 字匯:
![image](https://user-images.githubusercontent.com/8191296/61479134-bc0b0100-a9c5-11e9-84df-36807618ef1e.png)

which states it is an old form of "肅".  Both are severe corruptions of the old Hanzi forms, so neither form is better than the other.

**Comment by wtn** [comment]
Thank you.
