### ISSUE TITLE
𠮷 U+20BB7 and 吉 U+5409

### ISSUE THREAD

**Issue by wtn** [hfhchan/irg#147]
@eisoch says they're not z-variants:
> U+20BB7 is the variant of 吉 U+5409 in modern Japanese, especially 野家, but it's also a place name character in Hunan Province, China, which is not related to 吉 U+5409 any more, so I think it's better to keep them in kSpoofingVariant.

**Comment by hfhchan** [comment]
The glyph has been updated on glyphwiki, the mapping in kVariants.md will be removed in a future data sync.
