### ISSUE TITLE
The License of this project

### ISSUE THREAD

**Issue by choznerol** [hfhchan/irg#208]
Hi. Thank you for creating and maintaining this project. I just noticed there is not a license specified for this repo, and I learned that by default nobody can reuse the code[^1]. Would you mind clarify the applicable license? Thanks!

[^1]: https://opensource.stackexchange.com/a/1721/28614

**Comment by hfhchan** [comment]
Please see the respective .md files for the LICENSE.

Files with no license specified are either all rights reserved or public data derived from other sources.

Please also note there is currently no code in this repository.
