### ISSUE TITLE
U+298CA should be 戍 on the right hand side

### ISSUE THREAD

**Issue by hfhchan** [hfhchan/irg#30]
![image](https://user-images.githubusercontent.com/8191296/30781185-2d1accaa-a14d-11e7-963a-0d3b663d88a4.png)

Glyph in Hanyu Dazidian:
![image](https://user-images.githubusercontent.com/8191296/30781191-445c6450-a14d-11e7-9c1c-02ca13e01e2b.png)

**Comment by eisoch** [comment]
G glyph should be modified, but there is no need to disunify.

**Comment by hfhchan** [comment]
Glyph in GB18030:
![image](https://user-images.githubusercontent.com/8191296/38010128-3b2f47e8-328a-11e8-8d8c-b726c31e2ce0.png)

**Comment by hfhchan** [comment]
Refer to #73 , the normalization of phonetic component is correct, Hanyu Dazidian is wrong.
