### ISSUE TITLE
TB-733E 𫝎 (U+2B74E) has been replaced in CNS11643

### ISSUE THREAD

**Issue by hfhchan** [hfhchan/irg#52]
![image](https://user-images.githubusercontent.com/8191296/35476311-b3fb7654-03e8-11e8-8cfc-130b552b7d11.png)

http://cns11643.gov.tw/AIDB/query_general_view.do?page=B&code=733E

![image](https://user-images.githubusercontent.com/8191296/35476312-bc2208ac-03e8-11e8-9823-3331069a367e.png)

**Comment by wtn** [comment]
The mismatch has been corrected.

https://www.cns11643.gov.tw/wordView.jsp?ID=750388

<img width="410" alt="2B74E" src="https://user-images.githubusercontent.com/35801/148486615-4bbf05c7-b0ee-4d38-bc95-1d695717c2b0.png">
