### ISSUE TITLE
䕈 (U+4548) in GB 18030 doesn't match G3-6B2F

### ISSUE THREAD

**Issue by mrhso** [hfhchan/irg#72]
Glyph in Code Chart:
![image](https://user-images.githubusercontent.com/13294467/36056770-2e78da12-0e42-11e8-9bde-a7a04d389402.png)
Glyph in GB 18030-2005:
![image](https://user-images.githubusercontent.com/13294467/36056786-5e0baa3e-0e42-11e8-8bf0-17c4ab845b60.png)
Glyph in GB 18030-2000:
![image](https://user-images.githubusercontent.com/13294467/36056805-952f4ec6-0e42-11e8-93d4-80cbb932e78a.png)
Glyph in SimSun:
![image](https://user-images.githubusercontent.com/13294467/36056827-cbe1dd12-0e42-11e8-9b41-4f755d74fa0c.png)

**Comment by hfhchan** [comment]
![image](https://user-images.githubusercontent.com/8191296/36066276-f8cf0120-0ee1-11e8-9835-58d544198d1d.png)

Scan of G3 (GB 7589-87) (source: https://blogs.adobe.com/CCJKType/2014/05/uni4548.html)

> Dr. Ken Lunde says:	
> May 9, 2014 at 7:13 AM	
> My contact in China, CHEN Zhuang (陈壮), who happens to be China’s primary representative to the 
> IRG, confirmed this GB 18030 representative glyph error.

**Comment by hfhchan** [comment]
Glyph in Hanyu Dazidian
![image](https://user-images.githubusercontent.com/8191296/36307735-6ac3a8f6-1358-11e8-9e60-2dd1714ccbf4.png)

**Comment by mrhso** [comment]
Fixed in GB18030-2022.
![image](https://user-images.githubusercontent.com/13294467/182158844-9b47a7b8-cbd3-4c1d-b93e-7291c4dedeab.png)
